[workspace]
members = [
    "crates/rhizz-core",
    "crates/rhizz-cli",
    "crates/rhizz-server",
    "crates/rhizz-wasm",
    "crates/rhizz-book",
]
resolver = "2"

# Clippy settings from Tris' recommendations. Credit goes to:
# https://www.namtao.com/rust-toolkit-2026/
[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
# Deny panics
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
