<script lang="ts">
import { page } from "$app/state";
import { get_example_projects } from "../../rhizz_wasm_wrapper";
import BookExampleView from "./BookExampleView.svelte";
import { type BookPayloadFile, decodeBookPayload } from "./payload";

// Standalone book-embed route: renders a temporary project purely in the
// browser. It deliberately never touches `projectStore`/VFS — even when the
// app runs against `rhizz-server` persistence — so book readers can't read
// or clobber anyone's workspace.
//
// Sources (first match wins):
//   1. `#p=<base64url(deflate(json))>` location hash (generated by rhizz-book)
//   2. `?example=<id>` — one of the compiled-in worked examples
// `?open=<path>` optionally selects the initial tab and file/diagram.
let files = $state<BookPayloadFile[] | null>(null);
let payloadError = $state<string | null>(null);
let openParam = $derived.by((): string | null => {
  const raw = page.url.searchParams.get("open");
  return raw === null || raw === "" ? null : raw;
});

$effect(() => {
  const hash = page.url.hash;
  const example = page.url.searchParams.get("example");
  let cancelled = false;

  if (hash.startsWith("#p=")) {
    void decodeBookPayload(hash).then(
      (payload) => {
        if (cancelled) return;
        files = payload.files;
        payloadError = null;
      },
      (error: unknown) => {
        if (cancelled) return;
        files = null;
        payloadError = error instanceof Error
          ? error.message
          : "Unknown payload error";
      },
    );
    return () => {
      cancelled = true;
    };
  }

  if (example) {
    try {
      const found = get_example_projects().find((project) =>
        project.id === example
      );
      if (found) {
        files = found.files.map((file) => ({
          path: file.path,
          content: file.content,
        }));
        payloadError = null;
      } else {
        files = null;
        payloadError = `Unknown example "${example}"`;
      }
    } catch (error) {
      files = null;
      payloadError = error instanceof Error
        ? error.message
        : "Failed to load example";
    }
    return;
  }

  files = null;
  payloadError = null;
});
</script>

<!-- Chromeless takeover like the diagram embed route: covers the root layout's
     navbar so the iframe shows only the example. -->
<div
  class="fixed inset-0 z-40 w-screen h-screen bg-base-100 flex flex-col overflow-hidden">
  {#if payloadError}
    <div class="flex-1 flex items-center justify-center p-6">
      <div role="alert" class="alert alert-error max-w-lg">
        {payloadError}
      </div>
    </div>
  {:else if files}
    <BookExampleView {files} open={openParam} />
  {:else if payloadError === null}
    <div class="flex-1 flex items-center justify-center p-6">
      <div role="alert" class="alert alert-warning max-w-lg">
        No system data passed to the example endpoint. If you're browsing
        the documentation, please notify the Rhizz team about this issue!
      </div>
    </div>
  {:else}
    <div class="flex-1 flex items-center justify-center text-sm text-base-content/60">
      Loading example…
    </div>
  {/if}
</div>
