//! Diagnostic types — codes, severity, and structured diagnostic messages.

use serde::Serialize;

// ── Level ─────────────────────────────────────────────────────────────────────

/// The severity level of a diagnostic, modelled after the Rust compiler's own
/// `Level` type.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Level {
    /// An error that causes compilation to fail.
    Error,
    /// A warning — does not prevent compilation.
    Warning,
    /// A note — additional context attached to another diagnostic.
    Note,
    /// A help message — suggests how to fix something.
    Help,
}

impl Level {
    /// Returns `true` if this level blocks compilation.
    #[must_use]
    pub fn is_blocking(self) -> bool {
        self == Self::Error
    }
}

// ── WarningLevel ──────────────────────────────────────────────────────────────

/// The level of detail a project is specified at.
///
/// A *warning level* selects how much feedback the compiler reports: higher
/// levels demand more detail and therefore report more warnings. Levels are
/// cumulative — a warning declared at [`WarningLevel::Business`] is also
/// reported at `Architectural` and `Component` — so they form a total order
/// from least to most detailed.
///
/// Errors are never gated by a warning level; they are reported everywhere.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
pub enum WarningLevel {
    /// Business-level spec: super high-level, almost no detail requirements.
    Business,
    /// Architectural spec: high-level overview of the architecture.
    Architectural,
    /// Component-level spec: component overview touching low-level details.
    ///
    /// The default, so compilation without an explicit level keeps reporting
    /// every warning.
    #[default]
    Component,
}

impl WarningLevel {
    /// Every warning level, ordered from least to most detailed.
    pub const ALL: [Self; 3] = [Self::Business, Self::Architectural, Self::Component];

    /// Returns `true` when `code` should be reported at this warning level.
    ///
    /// Errors are reported at every level; a warning is reported once `self`
    /// has reached the code's [`DiagnosticCode::min_warning_level`].
    #[must_use]
    pub fn reports(self, code: DiagnosticCode) -> bool {
        if code.is_error() {
            return true;
        }
        code.min_warning_level <= self
    }
}

impl std::fmt::Display for WarningLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::Business => "business",
            Self::Architectural => "architectural",
            Self::Component => "component",
        })
    }
}

impl std::str::FromStr for WarningLevel {
    type Err = ParseWarningLevelError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value.trim().to_ascii_lowercase().as_str() {
            "business" => Ok(Self::Business),
            "architectural" => Ok(Self::Architectural),
            "component" => Ok(Self::Component),
            other => Err(ParseWarningLevelError(other.to_owned())),
        }
    }
}

/// Returned when a string does not name a known [`WarningLevel`].
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("unknown warning level '{0}' (expected one of: business, architectural, component)")]
pub struct ParseWarningLevelError(String);

// ── DiagnosticCode ────────────────────────────────────────────────────────────

/// A named diagnostic code with its severity baked in as a field.
///
/// Each code is a `pub const` on this type, so the level is the single source
/// of truth — no separate match arm needed when adding a new code.
///
/// The `code` string (e.g. `"E001"`) is stable and forms part of the public
/// API.  Renumbering is a breaking change.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct DiagnosticCode {
    /// Short code string, e.g. `"E001"` or `"W003"`.
    pub code: &'static str,
    /// Severity level — baked in at definition time.
    pub level: Level,
    /// Least-detailed [`WarningLevel`] at which this code is reported.
    ///
    /// Declared per code in `SPEC/diagnostics/*.md` and generated by
    /// `build.rs`. Error codes carry [`WarningLevel::Business`] and bypass
    /// level gating entirely — see [`WarningLevel::reports`].
    pub min_warning_level: WarningLevel,
}

include!(concat!(env!("OUT_DIR"), "/diagnostic_codes.rs"));

impl DiagnosticCode {
    /// Returns `true` if this code is error-level.
    #[must_use]
    pub fn is_error(self) -> bool {
        self.level == Level::Error
    }

    /// Returns `true` if this code is warning-level.
    #[must_use]
    pub fn is_warning(self) -> bool {
        self.level == Level::Warning
    }
}

impl std::fmt::Display for DiagnosticCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.code)
    }
}

impl Serialize for DiagnosticCode {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(&self.to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn warning_levels_order_from_least_to_most_detailed() {
        assert!(WarningLevel::Business < WarningLevel::Architectural);
        assert!(WarningLevel::Architectural < WarningLevel::Component);
        assert_eq!(WarningLevel::ALL.len(), 3);
    }

    #[test]
    fn default_warning_level_is_the_most_detailed() {
        assert_eq!(WarningLevel::default(), WarningLevel::Component);
    }

    #[test]
    fn warning_level_round_trips_through_display_and_from_str() {
        for level in WarningLevel::ALL {
            let rendered = level.to_string();
            assert_eq!(rendered.parse::<WarningLevel>(), Ok(level), "{rendered}");
        }
    }

    #[test]
    fn warning_level_parsing_is_case_insensitive_and_trims() {
        assert_eq!(
            "  BUSINESS ".parse::<WarningLevel>(),
            Ok(WarningLevel::Business)
        );
        assert_eq!(
            "Architectural".parse::<WarningLevel>(),
            Ok(WarningLevel::Architectural)
        );
    }

    #[test]
    fn unknown_warning_level_is_rejected_with_the_expected_message() {
        let error = "verbose".parse::<WarningLevel>().unwrap_err();
        assert_eq!(
            error.to_string(),
            "unknown warning level 'verbose' (expected one of: business, architectural, component)"
        );
    }

    #[test]
    fn errors_are_reported_at_every_warning_level() {
        for level in WarningLevel::ALL {
            assert!(level.reports(DiagnosticCode::E000), "{level}");
            assert!(level.reports(DiagnosticCode::E014), "{level}");
        }
    }

    #[test]
    fn business_level_warnings_are_reported_at_every_warning_level() {
        for level in WarningLevel::ALL {
            assert!(level.reports(DiagnosticCode::W014), "{level}");
        }
    }

    #[test]
    fn component_level_warnings_are_reported_only_at_the_most_detailed_level() {
        assert!(!WarningLevel::Business.reports(DiagnosticCode::W004));
        assert!(!WarningLevel::Architectural.reports(DiagnosticCode::W004));
        assert!(WarningLevel::Component.reports(DiagnosticCode::W004));
    }

    #[test]
    fn architectural_level_warnings_are_hidden_from_business_specs() {
        assert!(!WarningLevel::Business.reports(DiagnosticCode::W001));
        assert!(WarningLevel::Architectural.reports(DiagnosticCode::W001));
        assert!(WarningLevel::Component.reports(DiagnosticCode::W001));
    }
}

// ── Diagnostic ────────────────────────────────────────────────────────────────

/// A diagnostic message emitted during parsing, resolution, or validation.
#[derive(Debug, Clone, Serialize)]
pub struct Diagnostic {
    /// Diagnostic code identifying the class of error or warning.
    pub code: DiagnosticCode,
    /// Source file path, if known.
    pub file: Option<std::path::PathBuf>,
    /// Source line number, if known.
    pub line: Option<u32>,
    /// Human-readable diagnostic message.
    pub message: String,
}

impl Diagnostic {
    /// Create an error-level diagnostic.
    pub fn error(code: DiagnosticCode, message: impl Into<String>) -> Self {
        Self {
            code,
            file: None,
            line: None,
            message: message.into(),
        }
    }

    /// Create a warning-level diagnostic.
    pub fn warning(code: DiagnosticCode, message: impl Into<String>) -> Self {
        Self {
            code,
            file: None,
            line: None,
            message: message.into(),
        }
    }

    /// Returns `true` if this is an error diagnostic.
    #[must_use]
    pub fn is_error(&self) -> bool {
        self.code.is_error()
    }

    /// Returns `true` if this is a warning diagnostic.
    #[must_use]
    pub fn is_warning(&self) -> bool {
        self.code.is_warning()
    }
}
