[package]
name = "rhizz-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rhizz"
path = "src/main.rs"

[dependencies]
rhizz-core = { path = "../rhizz-core" }
rhizz-dot  = { path = "../rhizz-dot" }
anyhow     = "1"
walkdir    = "2"
serde      = { version = "1", features = ["derive"] }
clap       = { version = "4", features = ["derive"] }
owo-colors = "4"
serde_json = "1"

[dev-dependencies]
tempfile = "3"
